name: CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt

      - name: Build with Maven
        run: mvn clean install --batch-mode --no-transfer-progress

      - name: Run tests
        run: mvn test --batch-mode --no-transfer-progress